title: Sentient Commons
description: A post-capitalist digital sanctuary.
url: "https://www.sentientcommons.org"
baseurl: "/sentient-commons"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

logo: "/assets/images/sentient_commons_logo.png"

author:
  name: "Brandon G. Fiquett"
  avatar: "/assets/images/sigils_grid.png"
  bio: "Reprogrammer of systems. Designer of post-capitalist infrastructure."
  location: "Seattle, WA"
  email: your@email.com

defaults:
  -
    scope:
      path: ""
    values:
      layout: single
      author_profile: true

include:
  - _pages