title: Sentient Commons
description: A post-capitalist digital sanctuary.
url: "https://www.sentientcommons.org"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

logo: "/assets/images/eye-of-the-commons.png"

sass:
  style: compressed



author:
  name: "Brandon G. Fiquett"
  avatar: "/assets/images/brandon-avatar.png"
  bio: "Reprogrammer of systems. Designer of post-capitalist infrastructure."
  location: "Seattle, WA"
  email: brandon@fiquett.com

defaults:
  -
    scope:
      path: ""
    values:
      layout: single
      author_profile: true

include:
  - _pages